### PR TITLE
Disable login button before captcha valitation

### PR DESCRIPTION
**Pull request by bluantinoo**

### CODE REVIEW

**Comment by cyberscribe** [comment]
Thanks!

**Comment by cyberscribe** [comment]
I have refactored this to use javascript without jQuery, since not all login screens have jQuery enabled on them.

**Comment by bluantinoo** [comment]
nice :)

**Comment by bluantinoo** [comment]
you forgot to update the rep here :)

**Comment by cyberscribe** [comment]
Oops! Thanks.

eae2391084607bb050696c6e4afad502d3e628c1

**Pull request merged**
