### PR TITLE
Add recaptcha to  'Lost password' form

### PR DESCRIPTION
**Pull request by pavelpanasenko**

### CODE REVIEW

**Comment by cyberscribe** [comment]
Great, thanks for this--and it has been fully tested?

**Comment by pavelpanasenko** [comment]
Yes, it works like a charm.

**Comment by cyberscribe** [comment]
Thanks!

**Comment by cyberscribe** [comment]
Thanks!

**Comment by cyberscribe** [comment]
Hi Pavel,

Actually, moments after releasing this I realise it's only a front-end
change--there is no back-end checking of the captcha for the lost password
form.

So, this can be defeated by just removing disabled="disabled" from the
submit button, not checking the reCaptcha box, and submitting the email--it
goes through fine.

So, please work on the back-end if you would like to see this feature
realised. I will push the roll-back version to GitHub now.

Best,
Robert

**Pull request merged**
