### PR TITLE
Added whitelist functionality

### PR DESCRIPTION
**Pull request by farley1122**
Added functionality to whitelist ip addresses from reCAPTCHA authorizing.

### CODE REVIEW

**Comment by cyberscribe** [comment]
Thanks for this. 

Unfortunately, checking REMOTE_ADDR will not work in a variety of cases, including when a site is behind a proxy or load balancer. Instead we must implement a more comprehensive approach, such as: https://stackoverflow.com/questions/1634782/what-is-the-most-accurate-way-to-retrieve-a-users-correct-ip-address-in-php/2031935#2031935

Also, we ought to validate IP addresses somehow upon submission, and check the trim() of the string carefully to not include any blanks (e.g. does explode on all \r\n work on Mac/PC/*nix browsers?). Also, it would be nice to optionally display a message that the IP was found in the whitelist if we are not going to display the captcha.

Finally, there is no need to support v3 keys; this will be going away in a future release as v3 is really not suitable to login/registration/forgot password pages as I have found race conditions in real-world testing that make it less reliable than checkbox captchas.

Thanks again for your contribution; looking forward to the updated version!

**Comment by farley1122** [comment]
No problem.

-I had thought about the issue with REMOTE_ADDR not always returning the client IP, if for example they are using a proxy, but on the other hand if they are using a proxy and get the captcha, then the whitelist is technically working as intended because they didn't whitelist the proxy IP. I'm not sure about other cases like a load balancer but it seems like as long as the client is using the correct IP it would work.

Still, I've implemented the more thorough IP checking method though there's no 100% perfect way to always get the real client ip. ( Note: because of the strict checking, your ip may be invalid on a local testing environment )

-Good point, I've added a filter to trim each line so there are no blanks or invalid characters.

-As for IP validation, I don't think it needs any complicated procedure/validation, because if none of the IP address strings match up with the client ip, then it will simply show the user the captcha like normal.

-explode() should work on all servers running php 4 and higher, and according to the HTML5 spec, the value property of the textarea element should return '\r\n' for a newline. This appears to be true for all platforms. Tested via browserstack on Edge, IE, firefox, chrome, safari, opera, and yandex, as well as on android, IOS, mac, windows 10, windows 7, and windows xp.

-Sure, I've added a little message if the captcha was bypassed by the whitelist.

-I've also removed the v3 support.

**Comment by cyberscribe** [comment]
Great work @farley1122 -- I look forward to reviewing this and merging it in.

**Comment by cyberscribe** [comment]
Thanks!

**Comment by cyberscribe** [comment]
This will go live with v1.6 in the WP repository shortly.

**Comment by farley1122** [comment]
awesome :)

**Pull request merged**
